version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      # - ./data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    user: "999:999"
